[build]
  functions = ".netlify/functions"  # Corrected path
  publish = "public"

[[functions]]
  name = "typeScript Version for next use latest-release"
  ignore = true

[[redirects]]
  from = "/download/latest.zip"
  to = "/.netlify/functions/latest-release"
  status = 200
